apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frank2zgw.fullname" . }}-context
  labels:
    {{- include "frank2zgw.labels" . | nindent 4 }}
data:
  context.xml: {{ .Files.Get "files/context.xml" | quote }}
immutable: true