apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "frank2zgw.fullname" . }}
  labels:
    {{- include "frank2zgw.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.storage.storageClassName | quote }}
  accessModes:
    {{toYaml .Values.storage.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.storage.capacity }}