apiVersion: v1
entries:
  frank2zgw:
  - apiVersion: v2
    appVersion: 7.8-SNAPSHOT
    created: "2022-06-24T11:04:04.50208695+02:00"
    description: A Helm chart for running the Frank!Framework in Kubernetes
    digest: 0d6031f86e0cbe343a010502a5f6362a51f259c11f0bb05f2d2ea1bff821b9b6
    icon: https://raw.githubusercontent.com/ibissource/Frank2ZGW/master/favicon.svg
    name: frank2zgw
    type: application
    urls:
    - https://raw.githubusercontent.com/ibissource/Frank2ZGW/master/charts/frank2zgw-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    appVersion: 7.8-SNAPSHOT
    created: "2022-06-24T11:04:04.501438545+02:00"
    description: A Helm chart for running the Frank!Framework in Kubernetes
    digest: 00c71af05f642bee56da2d943bc9f7da6cfe78c6cd8cc1595ebe2cfaf45dc758
    icon: https://raw.githubusercontent.com/ibissource/Frank2ZGW/master/favicon.svg
    name: frank2zgw
    type: application
    urls:
    - https://raw.githubusercontent.com/ibissource/Frank2ZGW/master/charts/frank2zgw-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: 7.8-SNAPSHOT
    created: "2022-06-24T11:04:04.500895924+02:00"
    description: A Helm chart for running the Frank!Framework in Kubernetes
    digest: e03c40de766d520717f201083ab3b520b2da605b03651c8e8ac9281c9f944056
    icon: https://raw.githubusercontent.com/ibissource/Frank2ZGW/master/favicon.svg
    name: frank2zgw
    type: application
    urls:
    - https://raw.githubusercontent.com/ibissource/Frank2ZGW/master/charts/frank2zgw-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: 7.8-SNAPSHOT
    created: "2022-06-24T11:04:04.500227738+02:00"
    description: A Helm chart for Kubernetes
    digest: c2642ebce74e3e299e75b76aab61524a4166a711fc6ab2afa38b9edfb4906970
    icon: https://raw.githubusercontent.com/ibissource/Frank2ZGW/master/favicon.svg
    name: frank2zgw
    type: application
    urls:
    - https://raw.githubusercontent.com/ibissource/Frank2ZGW/master/charts/frank2zgw-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 7.8-SNAPSHOT
    created: "2022-06-24T11:04:04.499788112+02:00"
    description: A Helm chart for Kubernetes
    digest: 042915a8290d66bd1d8cda8eb1d2c2fce3995074d4b77b5f2c03c1cb2847e187
    icon: favicon.svg
    name: frank2zgw
    type: application
    urls:
    - https://raw.githubusercontent.com/ibissource/Frank2ZGW/master/charts/frank2zgw-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 7.8-SNAPSHOT
    created: "2022-06-24T11:04:04.499224135+02:00"
    description: A Helm chart for Kubernetes
    digest: 0a545f07563874cc502534fc0a43a914edad2eb0fe1bdb0930e1726dc9141afe
    icon: https://raw.githubusercontent.com/ibissource/Frank2ZGW/master/favicon.svg
    name: frank2zgw
    type: application
    urls:
    - https://raw.githubusercontent.com/ibissource/Frank2ZGW/master/charts/frank2zgw-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 7.8-SNAPSHOT
    created: "2022-06-24T11:04:04.498667214+02:00"
    description: A Helm chart for Kubernetes
    digest: b3a96fea7ac62e332df1845ef2353bffaa6f2ba9957fe2ac1cdaf27b5ae46375
    name: frank2zgw
    type: application
    urls:
    - https://raw.githubusercontent.com/ibissource/Frank2ZGW/master/charts/frank2zgw-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 7.8-SNAPSHOT
    created: "2022-06-24T11:04:04.49824538+02:00"
    description: A Helm chart for Kubernetes
    digest: 7efe18d7e17adf8b2db2994d537e1a3971abdfe7a7691938873a6cea159acd51
    name: frank2zgw
    type: application
    urls:
    - https://raw.githubusercontent.com/ibissource/Frank2ZGW/master/charts/frank2zgw-0.1.0.tgz
    version: 0.1.0
generated: "2022-06-24T11:04:04.497763917+02:00"
