apiVersion: v1
entries:
  frank2zgw:
  - apiVersion: v2
    appVersion: 7.8-SNAPSHOT
    created: "2022-06-23T15:33:56.285797673+02:00"
    description: A Helm chart for Kubernetes
    digest: b3a96fea7ac62e332df1845ef2353bffaa6f2ba9957fe2ac1cdaf27b5ae46375
    name: frank2zgw
    type: application
    urls:
    - https://raw.githubusercontent.com/ibissource/Frank2ZGW/master/charts/frank2zgw-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 7.8-SNAPSHOT
    created: "2022-06-23T15:33:56.285489495+02:00"
    description: A Helm chart for Kubernetes
    digest: 7efe18d7e17adf8b2db2994d537e1a3971abdfe7a7691938873a6cea159acd51
    name: frank2zgw
    type: application
    urls:
    - https://raw.githubusercontent.com/ibissource/Frank2ZGW/master/charts/frank2zgw-0.1.0.tgz
    version: 0.1.0
generated: "2022-06-23T15:33:56.28508048+02:00"
