apiVersion: v1
entries:
  frank2zgw:
  - apiVersion: v2
    appVersion: 7.8-SNAPSHOT
    created: "2022-06-23T16:20:13.271153271+02:00"
    description: A Helm chart for Kubernetes
    digest: c2642ebce74e3e299e75b76aab61524a4166a711fc6ab2afa38b9edfb4906970
    icon: https://raw.githubusercontent.com/ibissource/Frank2ZGW/master/favicon.svg
    name: frank2zgw
    type: application
    urls:
    - https://raw.githubusercontent.com/ibissource/Frank2ZGW/master/charts/frank2zgw-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 7.8-SNAPSHOT
    created: "2022-06-23T16:20:13.270845159+02:00"
    description: A Helm chart for Kubernetes
    digest: 042915a8290d66bd1d8cda8eb1d2c2fce3995074d4b77b5f2c03c1cb2847e187
    icon: favicon.svg
    name: frank2zgw
    type: application
    urls:
    - https://raw.githubusercontent.com/ibissource/Frank2ZGW/master/charts/frank2zgw-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 7.8-SNAPSHOT
    created: "2022-06-23T16:20:13.270511195+02:00"
    description: A Helm chart for Kubernetes
    digest: 0a545f07563874cc502534fc0a43a914edad2eb0fe1bdb0930e1726dc9141afe
    icon: https://raw.githubusercontent.com/ibissource/Frank2ZGW/master/favicon.svg
    name: frank2zgw
    type: application
    urls:
    - https://raw.githubusercontent.com/ibissource/Frank2ZGW/master/charts/frank2zgw-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 7.8-SNAPSHOT
    created: "2022-06-23T16:20:13.270184429+02:00"
    description: A Helm chart for Kubernetes
    digest: b3a96fea7ac62e332df1845ef2353bffaa6f2ba9957fe2ac1cdaf27b5ae46375
    name: frank2zgw
    type: application
    urls:
    - https://raw.githubusercontent.com/ibissource/Frank2ZGW/master/charts/frank2zgw-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 7.8-SNAPSHOT
    created: "2022-06-23T16:20:13.269806978+02:00"
    description: A Helm chart for Kubernetes
    digest: 7efe18d7e17adf8b2db2994d537e1a3971abdfe7a7691938873a6cea159acd51
    name: frank2zgw
    type: application
    urls:
    - https://raw.githubusercontent.com/ibissource/Frank2ZGW/master/charts/frank2zgw-0.1.0.tgz
    version: 0.1.0
generated: "2022-06-23T16:20:13.269361947+02:00"
