apiVersion: v2
type: application
name: frank2zgw
version: 0.1.5
appVersion: "7.8-SNAPSHOT"
description: A Helm chart for running the Frank!Framework in Kubernetes
icon: "https://raw.githubusercontent.com/ibissource/Frank2ZGW/master/favicon.svg"
