apiVersion: v2
type: application
name: frank2zgw
version: 0.1.4
appVersion: "7.8-SNAPSHOT"
description: A Helm chart for Kubernetes
icon: "https://raw.githubusercontent.com/ibissource/Frank2ZGW/master/favicon.svg"
