name: Lint and Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  docker:
    uses: ./.github/workflows/docker-build-and-push-workflow.yml
    secrets: inherit
    with:
      publish: >- 
        ${{ startsWith(github.ref, 'refs/tags/') ||
            (github.ref == 'refs/heads/main' &&
             github.event_name == 'push') }}
      docker-image-repo: docker.io/dogbytesgaming/open-zaakbrug