name: CI build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
  
    - uses: djbender/docker-buildx-pull-or-build@v0.5
    - name: Docker pull
      with:
          dockerfile: openzaak/open-zaak
        
    - uses: actions/checkout@v2
    - name: Docker build
      run: docker-compose up
    
